export const ADDTOCART = "ADDTOCART";
export const CURRENTITEM = "CURRENTITEM";
export const REMOVEFROMCART = "REMOVECART";
export const ADJUSTITEMQTY = "ADJUSTITEMQTY";
export const RESETCART = "RESETCART";